version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    ports:
      - "3000:80"
    container_name: frontend_app

  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_app:5432/migratecheck
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET_KEY="qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
      - FLYWAY_URL=jdbc:postgresql://postgres_app:5432/migratecheck
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=password
      - FLYWAY_LOCATIONS=classpath:db/migration
    depends_on:
      - postgres
    container_name: backend_app

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: migratecheck
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_app

volumes:
  postgres_data:
