version: '3.8'

networks:
  proj_network:
    driver: bridge

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    ports:
      - "3000:80"
    container_name: frontend_app
    depends_on:
      - backend
    networks:
      proj_network:
        aliases:
          - frontend

  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_app:5432/migratecheck
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
    container_name: backend_app
    networks:
      proj_network:
        aliases:
          - backend_app

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: migratecheck
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_app
    networks:
      proj_network:
        aliases:
          - postgres

volumes:
  postgres_data:
