name: Update Modules

on:
  schedule:
    - cron: '0 */2 * * *' # каждые 2 часа
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Check to update
        uses: actions/checkout@v2
        with:
          submodules: recursive 

      - name: Git author
        run: |
          git config --local user.email "palmalife99@gmail.com"
          git config --local user.name "dntbthrm"

      - name: Initialize submodules
        run: git submodule init

      - name: Update frontend submodule to 'develop' branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd frontend
          git fetch origin
          git checkout develop
          git pull origin develop
          cd ..

      - name: Update backend submodule
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd backend
          git pull origin main
          cd ..

      - name: Commit and push if there are changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update submodules"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/dntbthrm/p2p-review-2024.git main
