name: Update Modules

on:
  schedule:
    - cron: '0 */2 * * *' # раз в 2 часа
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Check to update
        uses: actions/checkout@v2
        with:
          submodules: recursive 
      - name: Configure Git author
        run: |
          git config --local user.email "palmalife99@gmail.com"
          git config --local user.name "dntbthrm"
      - name: Initialize submodules
        run: git submodule init
      - name: Update submodules
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git submodule update --remote
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update submodules"
            git push https://x-access-token:${GH_PAT}@github.com/dntbthrm/p2p-review-2024.git main
          fi
