name: Update Modules

on:
  schedule:
    - cron: '0 */2 * * *' # раз в 2 часа
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Check to update
        uses: actions/checkout@v2
        with:
          submodules: recursive 
      - name: Initialize submodules
        run: git submodule init
      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update submodules"
            git push origin main
          fi
